<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Candy Boatwright">

<title>CSI:Dixie Greenville</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="CSI_Greenville_HIST8510_Final_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="CSI_Greenville_HIST8510_Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="CSI_Greenville_HIST8510_Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="CSI_Greenville_HIST8510_Final_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CSI:Dixie Greenville</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Candy Boatwright </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readtext)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: NLP

Attaching package: 'NLP'

The following object is masked from 'package:ggplot2':

    annotate</code></pre>
</div>
</div>
<p>Stephen Berry in his 2022 book, Count The Dead, addresses the rise of the modern state and its correlation with the quantification of death. During the legislative session of 1849 a tremendous reform was passed through the United States Congress, almost by accident. As the last bill before the session adjourned for the year it received almost no review and was passed as speedily as possible.</p>
<p>The reform was the newly appointed U.S. Census Chair’s, Joseph C. G. Kennedy, implementation of a census questionnaire to be administered by federal agents traveling throughout the country. The questionnaire contained six schedules, the second was to record information on the enslaved persons living on a property including their names and place of birth. While Congress, especially those from southern states, beat the life out of Schedule 2, what they failed to act on was Schedule 3 which contained the questions to be asked about who had died on a property over the preceding year and what had caused their death. So, the first mortality census was born. (Berry, Count The Dead, 18-21)</p>
<p>The CSI:Dixie project produced by eHistory at the University of Georgia is based on coroners reports in the South primarily from the 19th century. Ten county datasets from South Carolina counties have been created to date. In this project, I begin by examining the Greenville County dataset to understand the implications of the information from the coroners’ inquests and then expand my focus to include Anderson, Chesterfield and Horry counties in order to examine regional similarities and differences. Through this examination the impact of the early economic development of these counties resulting in regional variances on public health becomes apparent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load CSI:Dixie Greenville County data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>CSI.GVL <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://docs.google.com/spreadsheets/d/e/2PACX-1vQzO3uN1w0-A_rN3bHuBWDr1iQe9hPZ68u7igu-I8wWDEpHSWH5T3AQFPvaa-VMSbuB8Z8X5wxSjmA6/pub?output=csv"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tidy data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>CSI.GVL.TIDY <span class="ot">&lt;-</span> CSI.GVL <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(NAME, <span class="fu">c</span>(<span class="st">"FIRST.NAME"</span>, <span class="st">"LAST.NAME"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="co">#separates first and last names</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(DATE, <span class="fu">c</span>(<span class="st">"MONTH"</span>, <span class="st">"DAY"</span>, <span class="st">"YEAR"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="co">#separates dates into month, day, year</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Additional pieces discarded in 9 rows [6, 9, 21, 22, 28, 58,
59, 89, 113].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Missing pieces filled with `NA` in 13 rows [8, 10, 16, 23,
30, 31, 33, 34, 39, 41, 42, 43, 66].</code></pre>
</div>
</div>
<p><strong>CSI:Greenville</strong></p>
<p>Greenville County was officially created in 1786. The land ceded from the Cherokee Nation after the Revolutionary War as well as lands confiscated from Loyalists became available for sale through the land grant office and was quickly bought up by newly independent Americans eager to reproduce the agricultural wealth of the lowcountry of South Carolina. The 1820s brought tremendous change as infrastructure became the focus of Greenville and so much of the state and nation as a whole. The State Road project was funded, connecting Greenville to Columbia and Charleston, as well as many bridge, ferry crossing and canal projects.</p>
<p>As South Carolina moved toward the middle of the 19th century, political strife began to characterize much of its residents’ interactions. Duels between white men were very often threatened, and (less often) occurred along the riverbanks and in old fields throughout the county. Despite the political turmoil of Nullification and Secession, industry continued to develop. The fast moving rivers coming out of the mountains were well suited to mill creation and the wealthy men able to purchase large tracts of land prized areas that lent themselves to diversified economic pursuits.</p>
<p>Until the beginning of the Civil War Greenville’s most important commodity was its location at the base of the Appalachians. The drover trade coming from Tennessee and Kentucky with livestock and other goods had a sophisticated network for alerting the livestock yards and merchants selling food and rest of their impending arrival. From the coast, the elite Charlestonians and lowcounty residents flocked to Greenville every summer to escape the disease and heat of the coast.</p>
<p>With the federal census reforms in 1850 there is an immediate impact on the data available in Greenville County. Coroner inquests increased dramatically from 1850 through the end of the 1880s, with the 1870s and 80s having the highest occurrences by a significant margin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Greenville by year</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>year.count <span class="ot">&lt;-</span> CSI.GVL.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(year.count, <span class="fu">aes</span>(<span class="at">x =</span> YEAR, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Greenville Inquests by Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The most obvious explanation is that some types of death increases would necessarily correspond with the Civil War. For example, the homicide and suicide rates during the 1850s and 60s are the highest compared to all other decades. What is interesting, however, is that the types of death that would seem as if there would not be a tremendous fluctuation due to war (ie: accidents and natural causes) also see a large spike during these decades. Of the accidents in Greenville that contain a description in the CSI:Dixie data almost all are related to vehicles such as wagons and trains.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Greenville deaths by type by year</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>by.year <span class="ot">&lt;-</span> CSI.GVL.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'YEAR'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(by.year, <span class="fu">aes</span>(<span class="at">x =</span> DEATH.TYPE, <span class="at">y =</span> count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>YEAR) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Greenville Death Type by Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#group by decade - create a new dataframe by decade and average death types over years within that decade"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>by.decade <span class="ot">&lt;-</span> CSI.GVL.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DECADE =</span> <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1800</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1810</span>, <span class="st">"Aughts"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1810</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1820</span>, <span class="st">"Tens"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1820</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1830</span>, <span class="st">"Twenties"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1830</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1840</span>, <span class="st">"Thirties"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1840</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1850</span>, <span class="st">"Forties"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1850</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1860</span>, <span class="st">"Fifties"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1860</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1870</span>, <span class="st">"Sixties"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1870</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1880</span>, <span class="st">"Seventies"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1880</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1890</span>, <span class="st">"Eighties"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1890</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>, <span class="st">"Nineties"</span>,                                   <span class="st">"Other"</span>))))))))))) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart DEATH.TYPE by DECADE</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>decade.count <span class="ot">&lt;-</span> by.decade <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DECADE, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'DECADE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(decade.count, <span class="fu">aes</span>(DEATH.TYPE, count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>DECADE) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Greenville Death by Decade"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In addition to the mode of death, the inquest data gives insight into the people dying in Greenville. It’s important to notice what information is not included, especially for black South Carolinians.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>age.sorted <span class="ot">&lt;-</span> CSI.GVL.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">AGE =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"child"</span>), <span class="st">"child"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"infant"</span>), <span class="st">"child"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"boy"</span>), <span class="st">"child"</span>, <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"son"</span>), <span class="st">"child"</span>, <span class="st">"adult"</span>)))))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(age.sorted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NAME FIRST.NAME     LAST.NAME DECEASED.DESCRIPTION
1      David Garison      David       Garison                     
2        black child      black         child          black child
3 John Pedeu[Peden?]       John Pedeu[Peden?]                     
4   Elizabeth Pinnel  Elizabeth        Pinnel                     
5       Samuel Bates     Samuel         Bates                     
6  negro woman slave      negro         woman    negro woman slave
               DATE    MONTH DAY YEAR                          INQUEST.LOCATION
1 February 23, 1823 February 23, 1823            [?] the house of David Garison
2     July 31, 1849     July 31, 1849                     at Morton's old place
3 February 11, 1851 February 11, 1851          at the house of John S. Pedeu[?]
4 February 27, 1851 February 27, 1851 at the late residence of Elizabeth Pinnel
5      July 9, 1851     July  9, 1851                        at McBride's Hotel
6     July 12, 1851     July 12, 1851                     at Jackson Pattison's
      DEATH.TYPE DEATH.METHOD     COUNTY   AGE
1       Accident              Greenville adult
2       Homicide              Greenville child
3       Homicide        rifle Greenville adult
4 Natural Causes              Greenville adult
5        Suicide     laudanum Greenville adult
6       Homicide              Greenville adult</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#adds sorting by race to dataframe previously sorted by age</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>all.sorted <span class="ot">&lt;-</span> age.sorted <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">RACE =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"black"</span>), <span class="st">"black"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"negro"</span>), <span class="st">"black"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"negroe"</span>), <span class="st">"black"</span>,                          <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"colored"</span>), <span class="st">"black"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"free"</span>), <span class="st">"black"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">if_else</span>(<span class="fu">str_detect</span>(DECEASED.DESCRIPTION, <span class="st">"slave"</span>), <span class="st">"black"</span>,                             <span class="st">"white"</span>)))))))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(all.sorted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NAME FIRST.NAME     LAST.NAME DECEASED.DESCRIPTION
1      David Garison      David       Garison                     
2        black child      black         child          black child
3 John Pedeu[Peden?]       John Pedeu[Peden?]                     
4   Elizabeth Pinnel  Elizabeth        Pinnel                     
5       Samuel Bates     Samuel         Bates                     
6  negro woman slave      negro         woman    negro woman slave
               DATE    MONTH DAY YEAR                          INQUEST.LOCATION
1 February 23, 1823 February 23, 1823            [?] the house of David Garison
2     July 31, 1849     July 31, 1849                     at Morton's old place
3 February 11, 1851 February 11, 1851          at the house of John S. Pedeu[?]
4 February 27, 1851 February 27, 1851 at the late residence of Elizabeth Pinnel
5      July 9, 1851     July  9, 1851                        at McBride's Hotel
6     July 12, 1851     July 12, 1851                     at Jackson Pattison's
      DEATH.TYPE DEATH.METHOD     COUNTY   AGE  RACE
1       Accident              Greenville adult white
2       Homicide              Greenville child black
3       Homicide        rifle Greenville adult white
4 Natural Causes              Greenville adult white
5        Suicide     laudanum Greenville adult white
6       Homicide              Greenville adult black</code></pre>
</div>
</div>
<p>In examining the coroners inquest from Greenville County it is clear that this practice of refusing to name or further identify black individuals trickled down from the highest governmental offices to the local levels. It is also clear that infants and children of undetermined race were often not named in the inquests.</p>
<p>Comparing the overall trends of the Greenville dataset with those from Anderson, Horry and Chesterfield provide additional insights. I chose these in an attempt to understand what regional differences account for the variation in numbers of inquests? If, as Berry claims, you can judge the effectiveness of government by the health of its citizens, what forces account for the variances in the recorded deaths across South Carolina during the 19th century? Also, Anderson’s dataset is very similar in size to Greenville, whereas Horry County is the smallest and Chesterfield is one of the largest so they provide a representative sample.</p>
<p><strong>CSI:Anderson</strong></p>
<p>Anderson County follows a very similar development pattern to Greenville after the Revolutionary War. Population expansion in the early 1800s caused the larger Pendleton District to be divided into Anderson and Pickens Districts. Like Greenville, Anderson is primarily agricultural with a healthy industrial economy due to the establishment of mills.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load Anderson County data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>CSI.ANDERSON <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://docs.google.com/spreadsheets/d/e/2PACX-1vSZ5lXF7WTLe71GUg6Z_h6HgtoeQJ6BX1JQ7H6IgkGvrXSqzxIh720ElLPeWmzoXytW2O9J7bgL82Kg/pub?output=csv"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>CSI.ANDERSON.TIDY <span class="ot">&lt;-</span> CSI.ANDERSON <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(NAME, <span class="fu">c</span>(<span class="st">"FIRST.NAME"</span>, <span class="st">"LAST.NAME"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="co">#separates first and last names</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(DATE, <span class="fu">c</span>(<span class="st">"MONTH"</span>, <span class="st">"DAY"</span>, <span class="st">"YEAR"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="co">#separates dates into month, day, year</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Additional pieces discarded in 31 rows [6, 8, 9, 17, 29, 32,
37, 39, 42, 54, 77, 80, 81, 84, 90, 97, 99, 101, 102, 111, ...].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Missing pieces filled with `NA` in 25 rows [4, 10, 24, 25,
40, 47, 48, 49, 55, 56, 57, 58, 59, 60, 61, 62, 63, 71, 110, 127, ...].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 3 pieces. Missing pieces filled with `NA` in 4 rows [13, 116, 125,
130].</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Anderson by year count</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>year.count.anderson <span class="ot">&lt;-</span> CSI.ANDERSON.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(year.count.anderson, <span class="fu">aes</span>(<span class="at">x =</span> YEAR, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Anderson Inquests by Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#group by decade - create a new dataframe by decade and average death types over years within that decade"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>by.decade.anderson <span class="ot">&lt;-</span> CSI.ANDERSON.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DECADE =</span> <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1800</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1810</span>, <span class="st">"Aughts"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1810</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1820</span>, <span class="st">"Tens"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1820</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1830</span>, <span class="st">"Twenties"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1830</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1840</span>, <span class="st">"Thirties"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1840</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1850</span>, <span class="st">"Forties"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1850</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1860</span>, <span class="st">"Fifties"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1860</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1870</span>, <span class="st">"Sixties"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1870</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1880</span>, <span class="st">"Seventies"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1880</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1890</span>, <span class="st">"Eighties"</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1890</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>, <span class="st">"Nineties"</span>,                                   <span class="st">"Other"</span>))))))))))) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Anderson by DEATH.TYPE</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>death.type.anderson <span class="ot">&lt;-</span> CSI.ANDERSON.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(death.type.anderson, <span class="fu">aes</span>(<span class="at">x =</span> DEATH.TYPE, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Anderson Death Type Ranked"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart DEATH.TYPE by DECADE</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>decade.count.anderson <span class="ot">&lt;-</span> by.decade.anderson <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DECADE, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'DECADE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(decade.count.anderson, <span class="fu">aes</span>(DEATH.TYPE, count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>DECADE) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Anderson Death by Decade"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>CSI:Chesterfield</strong></p>
<p>Chesterfield County lies on the South Carolina fall zone and shares a border with North Carolina. It was organized and its courthouse built in 1785. The advent of the steamboat linked Chesterfield with North Carolina and Winyah Bay in Georgetown, South Carolina and brought rapid prosperity in the 1820s when it became a stopover town on the Pee Dee River. Its economy still remained largely rural and agricultural until after the Civil War and the arrival of the railroads connecting its pine barren timber to outside markets. It experienced a 55% increase in population during the 1880’s leading up to its highest inquest count in 1894. For its true inquest high point in the 1950’s, though, there was no corresponding population spike.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load Chesterfield County data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>CSI.CHESTERFIELD <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://docs.google.com/spreadsheets/d/e/2PACX-1vSiyRbp_NP79e2pOWCwtrQRUFbZ0HrPkPI4XiR5qcREiRhq2ifqJGh0oKWSaB19GPgb2_Z5pzEOo6PN/pub?output=csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>CSI.CHESTERFIELD.TIDY <span class="ot">&lt;-</span> CSI.CHESTERFIELD <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(NAME, <span class="fu">c</span>(<span class="st">"FIRST.NAME"</span>, <span class="st">"LAST.NAME"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="co">#separates first and last names</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(DATE, <span class="fu">c</span>(<span class="st">"MONTH"</span>, <span class="st">"DAY"</span>, <span class="st">"YEAR"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="co">#separates dates into month, day, year</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Additional pieces discarded in 174 rows [1, 2, 3, 8, 12, 15,
17, 18, 25, 26, 35, 39, 40, 41, 49, 51, 56, 61, 62, 63, ...].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows [216, 298, 468,
498].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 3 pieces. Missing pieces filled with `NA` in 8 rows [232, 233, 269,
341, 410, 479, 482, 498].</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Chesterfield by year count</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>year.count.chesterfield <span class="ot">&lt;-</span> CSI.CHESTERFIELD.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(year.count.chesterfield, <span class="fu">aes</span>(<span class="at">x =</span> YEAR, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>, <span class="at">size=</span><span class="dv">5</span>)) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Chesterfield Inquests by Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#group by decade - create a new dataframe by decade and average death types over years within that decade"</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>by.decade.chesterfield <span class="ot">&lt;-</span> CSI.CHESTERFIELD.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DECADE =</span> <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1800</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1810</span>, <span class="st">"Aughts"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1810</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1820</span>, <span class="st">"Tens"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1820</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1830</span>, <span class="st">"Twenties"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1830</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1840</span>, <span class="st">"Thirties"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1840</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1850</span>, <span class="st">"Forties"</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1850</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1860</span>, <span class="st">"Fifties"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1860</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1870</span>, <span class="st">"Sixties"</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1870</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1880</span>, <span class="st">"Seventies"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1880</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1890</span>, <span class="st">"Eighties"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1890</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>, <span class="st">"Nineties"</span>,                                   <span class="st">"Other"</span>))))))))))) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Chesterfield by DEATH.TYPE</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>death.type.chesterfield <span class="ot">&lt;-</span> CSI.CHESTERFIELD.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(death.type.chesterfield, <span class="fu">aes</span>(<span class="at">x =</span> DEATH.TYPE, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Chesterfield Death Type Ranked"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart DEATH.TYPE by DECADE</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>decade.count.chesterfield <span class="ot">&lt;-</span> by.decade.chesterfield <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DECADE, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'DECADE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(decade.count.chesterfield, <span class="fu">aes</span>(DEATH.TYPE, count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>DECADE) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Chesterfield Death by Decade"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>CSI:Horry</strong></p>
<p>Horry County is the location of present day Myrtle Beach, South Carolina. The site of the first European settlement site in Winyah Bay in the 1530’s, its development through the colonial period was marked by its isolation. It did not develop into a coastal hub like Charleston and Beaufort because its low-lying swampy land made it less suitable for indigo and rice cultivation as well as its separation from the west and south by the Pee Dee Swamp. Its sparse population and isolation continued the Revolutionary War and into the antebellum period. Horry County experienced a 33% population boom in 1850 with a corresponding increase in the black enslaved population, but the black population always stayed significantly lower than the white. Small farm agriculture dominated the economy of Horry County through the antebellum period, but industries such as mills were much higher by comparison to much of the state.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load Horry County data</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>CSI.HORRY <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://docs.google.com/spreadsheets/d/e/2PACX-1vQLbn85PImxeinLSgyS-CXgm3uPgp663HrzzVLeqYPa40QIaWWADQcbnhZBKR7MSHHzNFPk9PWdrBrh/pub?output=csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>CSI.HORRY.TIDY <span class="ot">&lt;-</span> CSI.HORRY <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(NAME, <span class="fu">c</span>(<span class="st">"FIRST.NAME"</span>, <span class="st">"LAST.NAME"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="co">#separates first and last names</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(DATE, <span class="fu">c</span>(<span class="st">"MONTH"</span>, <span class="st">"DAY"</span>, <span class="st">"YEAR"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="co">#separates dates into month, day, year</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Additional pieces discarded in 9 rows [6, 8, 14, 18, 35, 36,
39, 40, 42].</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 2 pieces. Missing pieces filled with `NA` in 13 rows [2, 10, 11, 12,
15, 16, 17, 21, 22, 25, 27, 31, 32].</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Horry by year count</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>year.count.horry <span class="ot">&lt;-</span> CSI.HORRY.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(year.count.horry, <span class="fu">aes</span>(<span class="at">x =</span> YEAR, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Horry Inquests by Year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#group by decade - create a new dataframe by decade and average death types over years within that decade"</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>by.decade.horry <span class="ot">&lt;-</span> CSI.HORRY.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DECADE =</span> <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1800</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1810</span>, <span class="st">"Aughts"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1810</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1820</span>, <span class="st">"Tens"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1820</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1830</span>, <span class="st">"Twenties"</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1830</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1840</span>, <span class="st">"Thirties"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1840</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1850</span>, <span class="st">"Forties"</span>,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1850</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1860</span>, <span class="st">"Fifties"</span>,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1860</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1870</span>, <span class="st">"Sixties"</span>,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1870</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1880</span>, <span class="st">"Seventies"</span>,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1880</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1890</span>, <span class="st">"Eighties"</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">if_else</span>(YEAR <span class="sc">&gt;=</span> <span class="dv">1890</span> <span class="sc">&amp;</span> YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>, <span class="st">"Nineties"</span>,                                   <span class="st">"Other"</span>))))))))))) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart Horry by DEATH.TYPE</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>death.type.horry <span class="ot">&lt;-</span> CSI.HORRY.TIDY <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(death.type.horry, <span class="fu">aes</span>(<span class="at">x =</span> DEATH.TYPE, <span class="at">y =</span> count)) <span class="sc">+</span>  <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Horry Death Ranked"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chart DEATH.TYPE by DECADE</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>decade.count.horry <span class="ot">&lt;-</span> by.decade.horry <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DECADE, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'DECADE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(decade.count.horry, <span class="fu">aes</span>(DEATH.TYPE, count)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">90</span>,<span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">geom_col</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>DECADE) <span class="sc">+</span> <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Horry Death by Decade"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CSI_Greenville_HIST8510_Final_Project_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As points of comparison emerge from the data it is important to remember the two contributing factors to the recorded data gleaned from the coroners inquests. First, the state of public health that the inquests represent. Many cultural realities affect which people and deaths were examined by a coroner in 19th century South Carolina. For example, a woman who died during childbirth would most likely not have warranted a coroner’s report. Second, how recent the advent of the recording of death was in the 19th century. The mortality census is the first time that the United States attempted to keep track of the people and mode of death of its residents. Berry argues that the ability to quantify death, although flawed, contributed to the doubling of the life expectancy between 1850-1950.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#combines all tidy datasets for Greenville, Chesterfield, Anderson and Horry Counties. The reason I chose these three to compare to Greenville is geographical (from other areas of the state) and well as number of records available (Anderson is similar in size to Greenville, Chesterfield is one of the largest datasets and Horry the smallest)</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>COMBINED_CSI_TIDY <span class="ot">&lt;-</span> <span class="fu">rbind</span>(CSI.GVL.TIDY, CSI.ANDERSON.TIDY, CSI.CHESTERFIELD.TIDY, CSI.HORRY.TIDY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#shows the year with the largest number of inquests from each county</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>highest.year <span class="ot">&lt;-</span> COMBINED_CSI_TIDY <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COUNTY, YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'COUNTY'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>highest.year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   COUNTY [4]
  COUNTY       YEAR  count
  &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;
1 Anderson     1876     16
2 Chesterfield 1934     21
3 Greenville   1880     15
4 Horry        1857      6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limit the highest year to the 1800s - this is to adjust for Chesterfield being the only county with data into the 1900s as well as being the largest dataset</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>highest.year.filtered <span class="ot">&lt;-</span> COMBINED_CSI_TIDY <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COUNTY, YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(YEAR <span class="sc">&lt;</span> <span class="dv">1900</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'COUNTY'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>highest.year.filtered</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   COUNTY [4]
  COUNTY       YEAR  count
  &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;
1 Anderson     1876     16
2 Chesterfield 1894     17
3 Greenville   1880     15
4 Horry        1857      6</code></pre>
</div>
</div>
<p>Horry County saw its highest number of inquests in 1857 listing homicide as the cause of death. Anderson in 1876 with a majority of accidents, Greenville in 1880 with accidents and natural causes even, and Chesterfield County did not record its highest number until 1934 with natural causes listed as the leading cause of death. Horry, Anderson and Greenville follow the trend of the increase in inquests after the federal reform of 1850, but Chesterfield’s peak is almost a half century late. Even when limiting the data to the 19th century, Chesterfield’s highest year is 1894.</p>
<p>By more closely examining the individual records of the highest cause of death in the most documented decade in each county patterns begin to emerge especially around the treatment of black South Carolinians:</p>
<blockquote class="blockquote">
<p>Of the nine homicides between 1850-59, 2 were recorded by only a first name most likely indicating an African American individual.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#List all Horry County deaths in 1850-59 with death type descending</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>horry.fifties <span class="ot">&lt;-</span> by.decade.horry <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DECADE <span class="sc">==</span> <span class="st">"Fifties"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME, DECEASED.DESCRIPTION, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(DEATH.TYPE)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>horry.fifties</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 3
   NAME                 DECEASED.DESCRIPTION DEATH.TYPE    
   &lt;chr&gt;                &lt;chr&gt;                &lt;chr&gt;         
 1 W. H. Gordon         ""                   Accident      
 2 unknown negro        "unknown negro"      Accident      
 3 Wilson M. Gilligan   ""                   Accident      
 4 Hollan               ""                   Accident      
 5 Fanny                ""                   Accident      
 6 Titus                ""                   Accident      
 7 Jethro               ""                   Accident      
 8 Jack                 ""                   Homicide      
 9 William Milligan     ""                   Homicide      
10 John Rhodes          ""                   Homicide      
11 Edward Faircloth     ""                   Homicide      
12 Jim                  ""                   Homicide      
13 Irving Stallings     ""                   Homicide      
14 Elizabeth M. Skipper ""                   Homicide      
15 Michael Pertell      ""                   Homicide      
16 Enoch Stevens        ""                   Homicide      
17 unnamed infant       "unnamed infant"     Natural Causes
18 Silvia               ""                   Natural Causes
19 Martha G. Herring    ""                   Unknown       </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Of the eighteen accident related deaths in Anderson from 1870-79 only two are listed without first and last names. One is “Smith” and another is referred to only as “colored”. Of note, one of the individual listed is John Calhoun Clemson, Thomas Green and Anna Clemson’s son. He was killed in a railway accident near Seneca.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#List all Anderon County deaths in 1870-79 with death type descending</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>anderson.seventies <span class="ot">&lt;-</span> by.decade.anderson <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DECADE <span class="sc">==</span> <span class="st">"Seventies"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME, DECEASED.DESCRIPTION, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(DEATH.TYPE)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>anderson.seventies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 3
   NAME                 DECEASED.DESCRIPTION DEATH.TYPE
   &lt;chr&gt;                &lt;chr&gt;                &lt;chr&gt;     
 1 Allen Johnson        ""                   Accident  
 2 colored              "colored"            Accident  
 3 Eli David Junkins    ""                   Accident  
 4 George Hammond       ""                   Accident  
 5 Henry Thompson       ""                   Accident  
 6 James Jenkins        ""                   Accident  
 7 Jefferson Kitsinger  ""                   Accident  
 8 John Calhoun Clemson ""                   Accident  
 9 Lena Hutchinson      ""                   Accident  
10 M. J. Wilson         ""                   Accident  
# ℹ 38 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>There are thirteen accidents tied to a coroner’s report in the 1880’s in Greenville. There are none listed without surnames, but Julius Brockman is described as a black boy by in the CSI:Dixie data. The thirteen deaths described as natural causes are all recorded as first and last names.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#List all Greenville County deaths in 1880-89 with death type descending</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>greenville.eighties <span class="ot">&lt;-</span> by.decade <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DECADE <span class="sc">==</span> <span class="st">"Eighties"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME, DECEASED.DESCRIPTION, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(DEATH.TYPE)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>greenville.eighties</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 42 × 3
   NAME            DECEASED.DESCRIPTION DEATH.TYPE
   &lt;chr&gt;           &lt;chr&gt;                &lt;chr&gt;     
 1 Stephen Yeargin ""                   Accident  
 2 infant female   "infant female"      Accident  
 3 George Martin   ""                   Accident  
 4 R. Davis        ""                   Accident  
 5 Julius Brockman "negroe boy"         Accident  
 6 Rosa Blasingame ""                   Accident  
 7 John Lyons      ""                   Accident  
 8 Zilpha Fisher   ""                   Accident  
 9 Pressly Foster  "boy"                Accident  
10 Pauline Abraham "child"              Accident  
# ℹ 32 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Lastly, there are 58 deaths listed as natural causes in Chesterfield in the 1890’s. None of the deaths are listed with surnames or described as an African American individual.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#List all Chesterfield County deaths in 1890-99 with death type descending</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>chesterfield.nineties <span class="ot">&lt;-</span> by.decade.chesterfield <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DECADE <span class="sc">==</span> <span class="st">"Nineties"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME, DECEASED.DESCRIPTION, DEATH.TYPE) <span class="sc">%&gt;%</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(DEATH.TYPE)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>chesterfield.nineties</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 93 × 3
   NAME              DECEASED.DESCRIPTION DEATH.TYPE
   &lt;chr&gt;             &lt;chr&gt;                &lt;chr&gt;     
 1 Augusta Sullivan  ""                   Accident  
 2 Austin Dunlap     ""                   Accident  
 3 Beatrice McGuine  ""                   Accident  
 4 Ben F. Williams   ""                   Accident  
 5 Charity Goldplate ""                   Accident  
 6 Chas McQueen      ""                   Accident  
 7 Duncan Fleming    ""                   Accident  
 8 Edmond Long       ""                   Accident  
 9 Emanuel Courtney  ""                   Accident  
10 Eva Tucker        ""                   Accident  
# ℹ 83 more rows</code></pre>
</div>
</div>
<p><strong>Conclusion</strong></p>
<p>Although there is a great deal to be learned from assembling the coroner inquests that remain from the 19th century in South Carolina, in limiting my focus to a few counties that represent the different regions of that state it seems clear to me that the deaths directly coincide with the economies of these regions. Accidents and natural causes are the leading causes of death in Greenville, Anderson and Chesterfield during their peak decades of recorded coroner inquests. Accidents, especially industrial and vehicle accidents, are the top listed causes of death in the Piedmont region in the 1870-80s. This directly corresponds to the years after the Civil War and the rebuilding of a more industrialized economy. The natural deaths in Chesterfield in the 1890s speaks to the lack of industry and rural nature of that region, especially after the devastation of the Civil War. Horry County is a bit of an outlier, but again, examining its early economic development the rate of homicides during the 1850s and the relatively high percentage of black deaths, this can be seen through the lens of plantation economics as well as the slave uprisings in the days leading up to Civil War.</p>
<p><strong>Bibliography</strong></p>
<p>Berry, Stephen. <em>Count the Dead: Coroners, Quants, and the Birth of Death As We Know It.</em> Chapel Hill, North Carolina: University of North Carolina Press, 2022.</p>
<p>Edgar, Walter. <em>South Carolina: A History.</em> Columbia, S.C.: University of South Carolina Press, 1999.</p>
<p>Huff Jr., Archie Vernon. <em>Greenville: The History of the City and County in the South Carolina Piedmont.</em> Columbia, S.C.: University of South Carolina Press, 1995.</p>
<p>Lewis, Catherine H. <em>Horry County, South Carolina, 1730-1993.</em> Columbia, S.C.: University of South Carolina Press, 1998.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>